# 应用名称
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: dream_boot

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms


  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称

    name: defaultDataSource
  # 数据库连接地址
  datasource.url: jdbc:mysql://localhost:3306/dream?serverTimezone=Asia/Shanghai
  # 数据库用户名&密码：
  datasource.username: root
  datasource.password: 123456
# 应用服务 WEB 访问端口
server:
  port: 7777

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wangyuhang.dream_boot.entity


# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true

aliyun:
  accessKeyId: 7
  accessKeySecret: 7
  bucketName: 7
  endPoint: oss-cn-hangzhou.aliyuncs.com
  fileHost: dream
  urlPrefix: 7




